main.cpp
Ax
Referenced by _tmain.
Bx
Referenced by _tmain.
CAMERA_SEARCH
Referenced by _tmain.
CAMERA_ID
Referenced by _tmain.
DRAWING_CONFIG_WINDOW
Referenced by _tmain.
PROGRAM_WINDOW
Referenced by _tmain.
TYPE_CIRCLE
Referenced by _tmain, createDrawWindow, drawModel.
TYPE_RECT
Referenced by _tmain, createDrawWindow, drawModel.
TYPE_RECT2
Referenced by drawModel.
MAX_DRAWING_CIRCLE_RADIUS
Referenced by createDrawWindow.
MAX_DRAWING_RECT_BASE
Referenced by createDrawWindow.
MAX_DRAWING_RECT_HEIGHT
Referenced by createDrawWindow.
MAX_FONT_TYPE
Referenced by createDrawWindow.
MAX_FONT_SCALE
Referenced by createDrawWindow.
MAX_TEXT_OFFSET
Referenced by createDrawWindow.
MAX_LEFT_TEXT_OFFSET
OUTLINE_COLOR
Referenced by drawModel.
OUTLINE_THICKNESS
Referenced by drawModel.
TEXT_THICKNESS
Referenced by drawModel.
FULL_WHEIGHT
Referenced by drawModel.
THREE_FOURTHS_WHEIGHT
Referenced by drawModel.
HALF_WHEIGHT
ONE_FOURTH_WHEIGHT
NO_WHEIGHT
Referenced by drawModel.
szWidth
Referenced by _tmain.
szHeight
Referenced by _tmain.
deltaGaussianBlur
Referenced by _tmain.
minHue
Referenced by _tmain, processamento.
minSat
Referenced by _tmain, processamento.
minVal
Referenced by _tmain, processamento.
maxHue
Referenced by _tmain, processamento.
maxSat
Referenced by _tmain, processamento.
maxVal
Referenced by _tmain, processamento.
maxPoints
Referenced by ajuste, processamento.
Trans
noTrans
AUTOBUSCA_ALTURA
Referenced by processamento.
AUTOBUSCA_LARGURA
Referenced by processamento.
PRECISAO_BUSCA
Referenced by ajuste.
MINIMAL_MATCH
Referenced by processamento.
AUTOBUSCA_PULO
Referenced by processamento.
APPROXIMATION
Referenced by processamento.
MIN_AREA
Referenced by processamento.
MAX_AREA
Referenced by processamento.
UNIDADE
Referenced by _tmain.
BASE
Referenced by _tmain.
HEIGHT
Referenced by _tmain.
OFFSETX
Referenced by _tmain.
OFFSETY
Referenced by _tmain.
OFFSETY_2RECT
Referenced by drawModel.
ERR_NO_CAMERA
Referenced by searchCam.
ERR_LOAD_CAMERA
Referenced by _tmain.
ERR_INITIAL_READ_FRAME
Referenced by _tmain.
ERR_READ_FRAME
Referenced by _tmain.
ERR_EMPTY_IMAGES
Referenced by _tmain.
int radius
Referenced by _tmain, createDrawWindow, drawModel.
int base
Referenced by _tmain, createDrawWindow, drawModel.
int height
Referenced by _tmain, createDrawWindow, drawModel.
int offsetX
Referenced by _tmain, createDrawWindow, drawModel.
int offsetY
Referenced by _tmain, createDrawWindow, drawModel.
int text_offsetX
Referenced by createDrawWindow, drawModel.
int text_offsetY
Referenced by createDrawWindow, drawModel.
int fontFace
Referenced by createDrawWindow, drawModel.
int scale
Referenced by createDrawWindow, drawModel.
int left_text
Referenced by createDrawWindow, drawModel.
int sizeCols
Referenced by _tmain, createDrawWindow.
int sizeRows
Referenced by _tmain, createDrawWindow.
string type
Referenced by _tmain.
int _szWidth
Referenced by _tmain, filter.
int _szHeight
Referenced by _tmain, filter.
int delta
Referenced by _tmain, filter.
int _minHue
Referenced by _tmain, proc, processamento.
int _minSat
Referenced by _tmain, proc, processamento.
int _minVal
Referenced by _tmain, proc, processamento.
int _maxHue
Referenced by _tmain, proc, processamento.
int _maxSat
Referenced by _tmain, proc, processamento.
int _maxVal
Referenced by _tmain, proc, processamento.
int searchCam(VideoCapture *camera)
References ERR_NO_CAMERA.
Referenced by _tmain.
void createDrawWindow(string name, string type)
References base, fontFace, height, left_text, MAX_DRAWING_CIRCLE_RADIUS, MAX_DRAWING_RECT_BASE, MAX_DRAWING_RECT_HEIGHT, MAX_FONT_SCALE, MAX_FONT_TYPE, MAX_TEXT_OFFSET, offsetX, offsetY, radius, scale, sizeCols, sizeRows, text_offsetX, text_offsetY, TYPE_CIRCLE, TYPE_RECT.
Referenced by _tmain.
Mat drawModel(string type, Mat image)
References base, fontFace, FULL_WHEIGHT, height, left_text, NO_WHEIGHT, offsetX, offsetY, OFFSETY_2RECT, OUTLINE_COLOR, OUTLINE_THICKNESS, radius, scale, text_offsetX, text_offsetY, TEXT_THICKNESS, THREE_FOURTHS_WHEIGHT, TYPE_CIRCLE, TYPE_RECT, TYPE_RECT2.
Referenced by _tmain.
void filter(Mat &src, Mat &dst)
References _szHeight, _szWidth, delta.
Referenced by _tmain.
void proc(Mat &src, Mat &dst)
References _maxHue, _maxSat, _maxVal, _minHue, _minSat, _minVal.
Referenced by ajuste, processamento.
Mat show(Mat src1, Mat src2, int percentage)
bool allOnes(Mat VcMat[], int VcSize, int numElements)
Referenced by ajuste.
void ajuste(int VcSize, Range MatRow[], Range MatCol[], int *properties[], Mat &src, Mat &dst)
References allOnes, maxPoints, PRECISAO_BUSCA, proc.
Referenced by processamento.
vector< vector< Point > > processamento(Mat HSV, Mat bin)
References _maxHue, _maxSat, _maxVal, _minHue, _minSat, _minVal, ajuste, APPROXIMATION, AUTOBUSCA_ALTURA, AUTOBUSCA_LARGURA, AUTOBUSCA_PULO, MAX_AREA, maxHue, maxPoints, maxSat, maxVal, MIN_AREA, minHue, MINIMAL_MATCH, minSat, minVal, proc.
Referenced by _tmain.
double calculation(vector< vector< Point >> region, Mat image)
Referenced by _tmain.
int _tmain(int argc, char **argv)
References _maxHue, _maxSat, _maxVal, _minHue, _minSat, _minVal, _szHeight, _szWidth, Ax, BASE, base, Bx, calculation, CAMERA_ID, CAMERA_SEARCH, createDrawWindow, delta, deltaGaussianBlur, DRAWING_CONFIG_WINDOW, drawModel, ERR_EMPTY_IMAGES, ERR_INITIAL_READ_FRAME, ERR_LOAD_CAMERA, ERR_READ_FRAME, filter, HEIGHT, height, maxHue, maxSat, maxVal, minHue, minSat, minVal, OFFSETX, offsetX, OFFSETY, offsetY, processamento, PROGRAM_WINDOW, radius, searchCam, sizeCols, sizeRows, szHeight, szWidth, type, TYPE_CIRCLE, TYPE_RECT, UNIDADE.